#version 450
#extension GL_EXT_nonuniform_qualifier : require

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 4, rgba8) uniform writeonly image2D destImage[];

layout(push_constant) uniform PushConstants {
    uint write_buffer_index;
    uint verify_buffer_index;
    uint unused1;
    uint unused2;
} pc;

void main(void) {
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
    vec4 color = vec4(0.0, 0.0, 1.0, 1.0);
    imageStore(destImage[pc.write_buffer_index], texelCoord, color);
}
