#version 450
#extension GL_EXT_nonuniform_qualifier : require

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(push_constant) uniform PushConstants {
    uint write_buffer_index;
    uint verify_buffer_index;
    uint unused1;
    uint unused2;
    uint unused3;
} pc;

struct TestData {
    vec4 data;
};

struct TestResult {
    vec4 success;
};

layout(std430, set = 0, binding = 5) buffer TestBuffer {
    TestData values[];
} buffers[];

layout(std430, set = 0, binding = 5) buffer VerifyBuffer {
    TestResult result;
} verify_buffers[];

void main() {
    uint index = gl_GlobalInvocationID.x;
    if (buffers[pc.write_buffer_index].values[index].data.x != float(index)) {
        verify_buffers[pc.verify_buffer_index].result.success.x = 0.0;
    } else {
        verify_buffers[pc.verify_buffer_index].result.success.x = 1.0;
    }
}
